# Generated by Django 4.1.5 on 2023-01-19 21:05

from django.db import migrations, models
import images.validators


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.FileField(upload_to='images/', validators=[images.validators.validate_file_type]),
        ),
    ]
